#Cloud SQL PostgreSQL)
services:
    db:
        image: postgres:15
        environment: 
            POSTGRES_USER: vidscribe
            POSTGRES_PASSWORD: vidscribe_local
            POSTGRES_DB: vidscribe
        ports:
            - 5432:5432

        volumes:
            - postgres_data:/var/lib/postgresql/data 
    cache: 
        image: redis:7.2
        ports:
            - 6379:6379

    pubsub:
        image:  gcr.io/google.com/cloudsdktool/cloud-sdk:emulators 
        command: gcloud beta emulators pubsub start --host-port=0.0.0.0:8085
        ports:
            - "8085:8085"

    gcs:
        image: fsouza/fake-gcs-server
        ports:
            - "4443:4443" 
        command: -scheme http -port 4443
    
volumes: 
 postgres_data: 
