# Downloading the video
import yt_dlp
import os
import re
from typing import TypedDict
from models import CaptionSegment



def download_video(video_url: str, job_id: str) -> str:
    """Download video to local temp storage. This downloads the video only.                                                                                                                                 
    
    Args:                                                                                                                                                                     
        video_url: Video URL or GCS path. Not necessarily a YouTube URL, as yt-dlp supports many platforms.
        job_id: Used to name the output file uniquely.                                                                                                                        
    
    Returns:                                                                                                                                                                  
        Local file path to the downloaded video.                                                                                                                              
    """
    output_path = f"/tmp/{job_id}.mp4"
    ydl_opts = {
        "format": "bestvideo[ext=mp4]/best[ext=mp4]",
        "outtmpl": output_path,
    }
    with yt_dlp.YoutubeDL(ydl_opts) as ydl:
        ydl.download([video_url])
    return output_path


def download_audio(video_url: str, job_id: str) -> str:
    """Download audio from a video URL to local temp storage.
    
    Args:
        video_url: Video URL or GCS path.
        job_id: Used to name the output file uniquely.
    
    Returns:
        Local file path to the downloaded audio.
    """
    output_path = f"/tmp/{job_id}.m4a"
    ydl_opts = {
        "format": "bestaudio[ext=m4a]",
        "writesubtitles": True,
        "writeautomaticsub": True,
        "subtitleslangs": ["en"],
        "subtitlesformat": "vtt",
        "outtmpl": output_path,
    }
    with yt_dlp.YoutubeDL(ydl_opts) as ydl:
        ydl.download([video_url])
    return output_path




def timestamp_to_seconds(timestamp: str) -> float:
    """Convert a VTT timestamp (e.g., "00:01:23.456") to total seconds as a float.
    
    Args:
        timestamp: A string representing the timestamp in VTT format.
    Returns:
        Total seconds as a float.
    """
    hours, minutes, seconds = timestamp.split(":")
    total_seconds = int(hours) * 3600 + int(minutes) * 60 + float(seconds.replace(",", "."))
    return total_seconds




def parse_vtt(caption_path: str) -> list[CaptionSegment]:
    """Parse a VTT caption file into a list of caption segments.                                                                                                                                                                             
    
    Args:                                                                                                                                                                     
        caption_path: Local file path to the VTT captions.
    
    Returns:                                                                                                                                                                  
        List of caption segments, each with start time, end time, and text.
    """
    segments: list[CaptionSegment] = []
    with open(caption_path, "r", encoding="utf-8") as f:
    # Skip till we find the first timestamp line, which indicates the start of the captions
        for line in f:                                                                                                                                                       
            if line.strip() == "":                                                                                                                                                    
                break  # end of header block 
        start = 0.0
        end = 0.0
        for line in f:
            if "-->" in line:
                start_str, end_str = line.split("-->")
                # split()[0] drops trailing VTT positioning metadata (e.g. "align:start position:0%")
                start = timestamp_to_seconds(start_str.strip().split()[0])  
                end = timestamp_to_seconds(end_str.strip().split()[0]) 
            else:
                # Can be multiple lines of text for a single caption, so we need to concatenate them until we hit a blank line
                # Autogenerated captions have HTML tags, need to remove them
                text = re.sub(r"<[^>]+>", "", line).strip()      
                while True:
                    try: 
                        next_line = next(f).strip()
                    except StopIteration:
                        break
                    if not next_line:
                        break
                    text += " " + next_line
                if text:  # Only add segments that have text
                    segments.append(CaptionSegment(start=start, end=end, text=text))
    return segments





def extract_captions(audio_path: str) -> list[CaptionSegment]| None:
    """Extract captions from the downloaded audio file.                                                                                                                                                                             
    
    Args:                                                                                                                                                                     
        audio_path: Local file path to the downloaded audio.
    
    Returns:                                                                                                                                                                  
        List of caption segments or None if no captions found and need to be extracted using Whisper. Each segment includes start time, end time, and text.
    """
    #captions check
    captions_path = re.sub(r"\.[^.]+$", ".en.vtt", audio_path)
    if os.path.exists(captions_path):
        return parse_vtt(captions_path)
    #Whisper transcription
    return None







if __name__ == "__main__":
    # Example usage
    video_url = "https://www.youtube.com/watch?v=DgXV8QSlI4U"
    job_id = "example-job-id"                                                                                                                                                 
    audio_path = download_audio(video_url, job_id)                                                                                                                            
    print(f"Audio downloaded to: {audio_path}")   
    captions = extract_captions(audio_path)                                                                                                                                   
    if captions is None:                   
        captions = transcribe_with_whisper(audio_path, language="en")                                                                                                                                       
    else:                         
        print(f"Found {len(captions)} segments")
        for segment in captions[:5]:                                                                                                                                          
            print(segment)  

