# Downloading the video
import yt_dlp
import os
import re
from typing import TypedDict



def download_video(video_url: str, job_id: str) -> str:
    """Download video to local temp storage.                                                                                                                                  
    
    Args:                                                                                                                                                                     
        video_url: Video URL or GCS path. Not necessarily a YouTube URL, as yt-dlp supports many platforms.
        job_id: Used to name the output file uniquely.                                                                                                                        
    
    Returns:                                                                                                                                                                  
        Local file path to the downloaded video.                                                                                                                              
    """
    output_path = f"/tmp/{job_id}.mp4"
    ydl_opts = {
        "format": "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]",
        "writesubtitles": True,
        "writeautomaticsub": True,
        "subtitleslangs": ["en"],
        "subtitlesformat": "vtt",
        "outtmpl": output_path,
    }
    with yt_dlp.YoutubeDL(ydl_opts) as ydl:
        ydl.download([video_url])
    return output_path


class CaptionSegment(TypedDict):
    start: float
    end: float
    text: str

def timestamp_to_seconds(timestamp: str) -> float:
    """Convert a VTT timestamp (e.g., "00:01:23.456") to total seconds as a float.
    
    Args:
        timestamp: A string representing the timestamp in VTT format.
    Returns:
        Total seconds as a float.
    """
    hours, minutes, seconds = timestamp.split(":")
    total_seconds = int(hours) * 3600 + int(minutes) * 60 + float(seconds.replace(",", "."))
    return total_seconds

def parse_vtt(caption_path: str) -> list[CaptionSegment]:
    """Parse a VTT caption file into a list of caption segments.                                                                                                                                                                             
    
    Args:                                                                                                                                                                     
        caption_path: Local file path to the VTT captions.
    
    Returns:                                                                                                                                                                  
        List of caption segments, each with start time, end time, and text.
    """
    segments: list[CaptionSegment] = []
    with open(caption_path, "r", encoding="utf-8") as f:
    # Skip till we find the first timestamp line, which indicates the start of the captions
        for line in f:                                                                                                                                                       
            if line.strip() == "":                                                                                                                                                    
                break  # end of header block 
        start = 0.0
        end = 0.0
        for line in f:
            if "-->" in line:
                start_str, end_str = line.split("-->")
                # split()[0] drops trailing VTT positioning metadata (e.g. "align:start position:0%")
                start = timestamp_to_seconds(start_str.strip().split()[0])  
                end = timestamp_to_seconds(end_str.strip().split()[0]) 
            else:
                # Can be multiple lines of text for a single caption, so we need to concatenate them until we hit a blank line
                # Autogenerated captions have HTML tags, need to remove them
                text = re.sub(r"<[^>]+>", "", line).strip()      
                while True:
                    try: 
                        next_line = next(f).strip()
                    except StopIteration:
                        break
                    if not next_line:
                        break
                    text += " " + next_line
                if text:  # Only add segments that have text
                    segments.append(CaptionSegment(start=start, end=end, text=text))
    return segments





# Find the captions, manual first then autogenerated, then whisper
def extract_captions(video_path: str) -> list[CaptionSegment]| None:
    """Extract captions from the downloaded video file.                                                                                                                                                                             
    
    Args:                                                                                                                                                                     
        video_path: Local file path to the downloaded video.
    
    Returns:                                                                                                                                                                  
        List of caption segments or None if no captions found and need to be extracted using Whisper. Each segment includes start time, end time, and text.
    """
    #captions check
    captions_path = video_path.replace(".mp4", ".en.vtt")
    if os.path.exists(captions_path):
        return parse_vtt(captions_path)
    #Whisper transcription
    return None







if __name__ == "__main__":
    # Example usage
    video_url = "https://www.youtube.com/watch?v=DgXV8QSlI4U&list=WL&index=26&t=19s"
    job_id = "example-job-id"
    local_video_path = download_video(video_url, job_id)
    print(f"Video downloaded to: {local_video_path}")
    captions = extract_captions(local_video_path)
    if captions is None:                                                                                                                                                      
        print("No captions found")
    else:
        print(f"Found {len(captions)} segments")                                                                                                                              
        for segment in captions[:5]:
            print(segment) 

